While working on partest discovered that CompilerCommand ignores half its constructor arguments and a couple dozen places blithely pass it those arguments as if they're being used.  Then there were setups like this:
class OfflineCompilerCommand(
  arguments: List[String],
  settings: Settings,
  error: String => Unit,
  interactive: Boolean)
extends CompilerCommand(arguments, new Settings(error), error, false)

Hey offline compiler command, why throw away the perfectly good
settings you were given? Ever heard 'reduce, reuse, recycle'? How
did you ever work... or do you? No review.

git-svn-id: http://lampsvn.epfl.ch/svn-repos/scala/scala/trunk@21274 5e8d7ff9-d8ef-0310-90f0-a4852d11357a